name: Keep SAP BTP App Alive

# 触发条件：每天UTC时间8点运行，同时允许手动触发
on:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC 8点自动运行，可根据需要调整
  workflow_dispatch:     # 允许手动触发

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cloud Foundry CLI
        run: |
          # 安装CF CLI
          wget -q -O cf.tgz "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=8&source=github"
          sudo tar -zxvf cf.tgz -C /usr/local/bin
          cf --version
          echo "CF CLI installed successfully"

      - name: Login to SAP BTP and access app
        id: btp-operations
        run: |
          echo "=== Starting SAP BTP operations ==="
          
          # 登录到SAP BTP
          cf login \
            -a "${{ secrets.CF_API_URL }}" \
            -u "${{ secrets.CF_USERNAME }}" \
            -p "${{ secrets.CF_PASSWORD }}" \
            -o "${{ secrets.CF_ORG }}" \
            -s "${{ secrets.CF_SPACE }}" \
            --skip-ssl-validation 2>&1 | tee /tmp/btp_operations.log
          
          # 获取应用列表（验证登录成功）
          echo "=== Retrieving app list ==="
          cf apps 2>&1 | tee -a /tmp/btp_operations.log
          
          # 如果知道应用名称，可以直接访问应用以保持活跃
          if [ -n "${{ secrets.APP_NAME }}" ]; then
            echo "=== Accessing app ${{ secrets.APP_NAME }} ==="
            APP_URL=$(cf app ${{ secrets.APP_NAME }} | grep -o 'https://[^ ]*')
            if [ -n "$APP_URL" ]; then
              curl -s -L -w "HTTP Status: %{http_code}\n" "$APP_URL" -o /dev/null 2>&1 | tee -a /tmp/btp_operations.log
              echo "Successfully accessed app URL: $APP_URL" | tee -a /tmp/btp_operations.log
            else
              echo "Could not retrieve URL for app ${{ secrets.APP_NAME }}" | tee -a /tmp/btp_operations.log
            fi
          fi

      - name: Save operation logs
        if: always()
        uses: actions/upload-artifact@v4  # 使用最新的v4版本
        with:
          name: btp-operation-logs
          path: /tmp/btp_operations.log
          retention-days: 7  # 日志保留7天
